services:
  - type: web
    name: cloudzone-app
    env: python
    region: oregon
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --workers 4 --bind 0.0.0.0:$PORT server:app
    envVars:
      - key: PYTHONUNBUFFERED
        value: 1
    autoDeploy: true
