services:
  - type: web
    name: cloudzone-app
    env: python
    region: oregon
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: python server.py
    envVars:
      - key: PYTHONUNBUFFERED
        value: 1
    autoDeploy: true
